config/routes.rb
Rails.application.routes.draw do

  get 'visitors/index'
  root 'dashboard#dashboard'
  resources :windows
  resources :apps
  resources :users
  resources :sessions, only: [:create, :destroy]
  resources :dev_teams
  get 'dashboard' => 'dashboard#dashboard'
  get 'dashboard/listapps' => 'dashboard#list_apps'
  get 'current-dashboard' => 'dashboard#load_user_dashboard'
  post 'dashboard/new/:name' => 'dash_settings#create_user_dashboard'
  post 'dashboard/:dashid/delete' => 'dash_settings#delete_dashboard'
  
  get '/window-proxy' => 'dashboard#window_proxy'

  get 'invite/:rand_token', to: 'users#invite_signup'
  post 'users/invite/new', to: 'users#invite_signup2'
  get '/invite', to: 'users#develop_invite'
  post 'invite', to: 'users#develop_invite2'
  post 'invite_dev_to_team', to: 'dev_teams#invite_to_dev_team'
  get 'exclude_dev_from_team', to: 'dev_teams#exclude_from_dev_team'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create2'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get '/new-notification-request' => 'notification_request#new_request'
  get '/notification-requests' => 'notification_request#see_requests'
  get '/notification-requests/:token_id' => 'notification_request#edit_request'
  post '/notification-requests' => 'notification_request#post_request'
  get '/delete-notification-request/:token_id' => 'notification_request#delete_request'
  get '/delete-notification-app/:not_app_id' => 'notification_request#delete_request_app'
  get '/new-request-app' => 'notification_request#new_request_application'
  post '/request-app' => 'notification_request#post_request_application'

  post '/register-user' => 'notifications#register_user'
  get '/push-notification' => 'notifications#push_notification_form'

  post '/push-notification-send' => 'notifications#push_notification_send'
  get '/push-notification-send-requested' => 'notifications#push_notification_send_requested'

  get '/new-notifications' => 'notifications#new_notifications'
  get '/last-notifications' => 'notifications#last_notifications'
  get '/last-from-sampadash' => 'notifications#last_from_sampadash'
  get '/load-last-notifications' => 'notifications#load_last_notifications'
  get '/load-last-from-sampadash' => 'notifications#load_last_from_sampadash'

  get '/dash_settings' => 'dash_settings#settings'
  post '/set_new_dash/:dashid' => 'dash_settings#set_current_dash'

end

app/models/window.rb
class Window < ApplicationRecord
  belongs_to :app
  belongs_to :user_dashboard
end

app/controllers/windows_controller.rb
class WindowsController < ApplicationController
  before_action :set_window, only: [:show, :edit, :update, :destroy]
  before_action :set_app, except: [:show, :destroy]
  before_action :set_dashboard
  before_action :authenticate_user
  before_action :verify_dashboard_owner
  before_action :verify_window_owner, except: [:index, :new, :create, :update]

  require 'open-uri'

  # GET /windows
  # GET /windows.json
  def index
    @windows = Window.all
  end

  # GET /windows/1
  # GET /windows/1.json
  def show
    redirect_to root_path and return
  end

  # GET /windows/new
  def new
    @window = current_app.windows.new(col: 1, row: 1, size_x: get_size_x, size_y: get_size_y, app_id: current_app.id, app_version: current_app.version, user_dashboard_id: current_dashboard.id)
  end

  # GET /windows/1/edit
  def edit
  end

  # POST /windows
  # POST /windows.json
  def create
    @window = current_app.windows.new(window_params)

    respond_to do |format|
      if @window.save
        format.html {redirect_to root_path, notice: 'Window was successfully created.'}
        format.json {render :show, status: :created, location: @window}
      else
        format.html {render :new}
        format.json {render json: current_app.errors, status: :unprocessable_entity}
      end
    end
  end
  
  # PATCH/PUT /windows/1
  # PATCH/PUT /windows/1.json
  def update
     @window.update(window_params)
     head :ok
  end

  # DELETE /windows/1
  # DELETE /windows/1.json
  def destroy
    @window.destroy
    head :ok
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_window
    @window = Window.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def window_params
    params[:window][:query_url] ||= get_query_url
    params.require(:window).permit(:col, :row, :size_x, :size_y, :query_url, :user_dashboard_id, :app_id, :app_version)
  end

  def get_query_url
    app_params = eval(current_app.parameters).keys
    query_params = params.require(:window).permit(app_params).to_h

    if current_app.base_url['?']
      current_app.base_url + '&' + CGI.unescape(query_params.to_query)
    else
      current_app.base_url + '?' + CGI.unescape(query_params.to_query)
    end
  end

  def get_size_x
    current_app.grid_size.split('x').map(&:to_i)[0]
  end

  def get_size_y
    current_app.grid_size.split('x').map(&:to_i)[1]
  end
end

app/helpers/windows_helper.rb
module WindowsHelper
end

app/views/windows/_form.html.erb
<%= form_with(model: window, local: true, class: 'form') do |form| %>
  <% if window.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(window.errors.count, "error") %> prohibited this window from being saved:</h2>

      <ul>
        <% window.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% eval(current_app.parameters).each do |key, value| %>
    <div class="field">
      <%= form.label key %>

      <% if value.class == Array %>
        <%= form.send(value[0], key, value[1], {}, {class: 'form-control'}) %>
      <% else %>
        <%= form.send(value, key, {class: 'form-control'}) %>
      <% end %>
    </div>
  <% end %>

  <%= form.hidden_field :col, value: @window.col %>
  <%= form.hidden_field :row, value: @window.row %>
  <%= form.hidden_field :size_x, value: @window.size_x %>
  <%= form.hidden_field :size_y, value: @window.size_y %>
  <%= form.hidden_field :app_id, value: @window.app_id %>
  <%= form.hidden_field :app_version, value: current_app.version %>
  <%= form.hidden_field :user_dashboard_id, value: @window.user_dashboard_id %>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/windows/edit.html.erb
<p id="notice"><%= notice %></p>

<h1>Editing Window</h1>

<%= render partial: 'apps/app', locals: {app: current_app} %>

<%= render 'form', window: @window %>

<%= link_to 'Show', @window %> |
<%= link_to 'Back', windows_path %>

app/views/windows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Windows</h1>

<table>
  <thead>
  <tr>
    <th>Col</th>
    <th>Row</th>
    <th>Size x</th>
    <th>Size y</th>
    <th>Query url</th>
  </tr>
  </thead>

  <tbody>
  <% @windows.each do |window| %>
    <tr>
      <td><%= window.col %></td>
      <td><%= window.row %></td>
      <td><%= window.size_x %></td>
      <td><%= window.size_y %></td>
      <td><%= window.query_url %></td>
      <td><%= link_to 'Show', window %></td>
      <td><%= link_to 'Edit', edit_window_path(window) %></td>
      <td><%= link_to 'Destroy', window, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Window', new_window_path %>

app/views/windows/new.html.erb
<%= render partial: 'apps/app', locals: {app: current_app} %>
<%= link_to 'Back', controller: 'apps', action: 'index', user_dashboard_id: current_dashboard.id %>

<hr class="hr-main">

<div class="content">

  <%= render 'form', window: @window %>
</div>