config/routes.rb
Rails.application.routes.draw do

  get 'visitors/index'
  root 'dashboard#dashboard'
  resources :windows
  resources :apps
  resources :users
  resources :sessions, only: [:create, :destroy]
  resources :dev_teams
  get 'dashboard' => 'dashboard#dashboard'
  get 'dashboard/listapps' => 'dashboard#list_apps'
  get 'current-dashboard' => 'dashboard#load_user_dashboard'
  post 'dashboard/new/:name' => 'dash_settings#create_user_dashboard'
  post 'dashboard/:dashid/delete' => 'dash_settings#delete_dashboard'
  
  get '/window-proxy' => 'dashboard#window_proxy'

  get 'invite/:rand_token', to: 'users#invite_signup'
  post 'users/invite/new', to: 'users#invite_signup2'
  get '/invite', to: 'users#develop_invite'
  post 'invite', to: 'users#develop_invite2'
  post 'invite_dev_to_team', to: 'dev_teams#invite_to_dev_team'
  get 'exclude_dev_from_team', to: 'dev_teams#exclude_from_dev_team'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create2'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get '/new-notification-request' => 'notification_request#new_request'
  get '/notification-requests' => 'notification_request#see_requests'
  get '/notification-requests/:token_id' => 'notification_request#edit_request'
  post '/notification-requests' => 'notification_request#post_request'
  get '/delete-notification-request/:token_id' => 'notification_request#delete_request'
  get '/delete-notification-app/:not_app_id' => 'notification_request#delete_request_app'
  get '/new-request-app' => 'notification_request#new_request_application'
  post '/request-app' => 'notification_request#post_request_application'

  post '/register-user' => 'notifications#register_user'
  get '/push-notification' => 'notifications#push_notification_form'

  post '/push-notification-send' => 'notifications#push_notification_send'
  get '/push-notification-send-requested' => 'notifications#push_notification_send_requested'

  get '/new-notifications' => 'notifications#new_notifications'
  get '/last-notifications' => 'notifications#last_notifications'
  get '/last-from-sampadash' => 'notifications#last_from_sampadash'
  get '/load-last-notifications' => 'notifications#load_last_notifications'
  get '/load-last-from-sampadash' => 'notifications#load_last_from_sampadash'

  get '/dash_settings' => 'dash_settings#settings'
  post '/set_new_dash/:dashid' => 'dash_settings#set_current_dash'

end

app/models/user.rb
class User < ApplicationRecord

  has_many :user_dashboards, dependent: :destroy
  has_many :dev_teams_users
  has_many :dev_teams, through: :dev_teams_users


  def self.from_omniauth(auth)
    user = User.find_by_email (auth.info.email)
    if (user)
      return user;
    end
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.email = auth.info.email
      user.usertype = 0
      user.save!
      dashboard = UserDashboard.new user_id: user.id, description: 'Default'
      dashboard.save!
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :verify_user_token, only: [:index]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:show, :edit, :update, :destroy, :index]
  #before_action :has_dev_permissions, only: [:show, :edit, :update, :destroy, :index]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.usertype = 0
    respond_to do |format|
      if @user.save
        dashboard = UserDashboard.new user_id: @user.id, description: 'Default'
        dashboard.save!
        log_in (@user)
        format.html {redirect_to root_path, notice: 'User was successfully created.'}
        format.json {render :show, status: :created, location: @user}
      else
        format.html {render :new}
        format.json {render json: @user.errors, status: :unprocessable_entity}
      end
    end
  end

  #get
  def develop_invite
    if (current_user == nil)
      respond_to do |format|
        format.html {redirect_to "/", notice: 'You must log in' and return}
      end
    end
    if (current_user.usertype == 0)
      respond_to do |format|
        format.html {redirect_to root_path, notice: 'You do not have the rights to invite a developer' and return}
      end
    end
    @user = User.new
  end

  #post
  def develop_invite2
    @temp = params[:user]
    user = User.all.find_by_email(@temp[:email])
    if (user != nil)
      if (user.usertype == 1)
        respond_to do |format|
          format.html {redirect_to root_path, notice: 'This email is already registered as a developer' and return}
        end
      else
        user.usertype = 1
        user.save!
      end
    else
      exist = Token.all.find_by_email(@temp[:email])
      if (exist)
        exist.delete
      end
      token = SecureRandom.uuid
      inv_by = (User.all.find_by_id(session[:user_id])).email
      invite = Token.new token: token, email: @temp[:email], invited_by: inv_by
      invite.save!
      @base = request.base_url
      if @base.include? "localhost"
        @iplocal = Socket.ip_address_list[1].ip_address
        @base = "http://"+@iplocal+":3000"
      end
      @reg_link = @base+"/invite/"+ token
      DevNotifierMailer.dev_invite(@temp[:email], @reg_link).deliver
      flash[:alert] = "Developer Invited"
      redirect_to root_path
    end

  end

  def invite_signup
    @id = Token.all.find_by_token(params[:rand_token])
    if (@id == nil)
      flash[:notice] = "Link invalido!"
      redirect_to '/' and return
    end
    @user = User.new()
  end


  def invite_signup2
    @user = User.new(user_params.permit(:name, :email, :token, :password))
    @user.usertype = 1
    @temp = params[:user]
    @id = Token.all.find_by_token(@temp[:token])
    @id.delete
    @user.save!
    log_in (@user)
    respond_to do |format|
      format.html {redirect_to root_path, notice: 'User was successfully created.' and return}
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html {redirect_to @user, notice: 'User was successfully updated.'}
        format.json {render :show, status: :ok, location: @user}
      else
        format.html {render :edit}
        format.json {render json: @user.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html {redirect_to users_url, notice: 'User was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)

  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password, class: 'form-control' %>
  </div>


  <div class="actions">

    <%= form.submit "Submit", class: 'btn login-button' %>
  </div>
<% end %>

app/views/users/develop_invite.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h2>Invite a developer</h2>

    <%= form_for(@user, :url => invite_path, :html => {:method => :post}) do |f| %>
      <div class="field">
        <%= f.label :email %><br/>
        <%= f.email_field :email, :required => true, class: "form-control" %>
      </div>
      <div class="actions v-space">
        <%= f.submit 'Complete sign up', class: "btn btn-info btn-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password</th>
    <th>Usertype</th>
    <th>Fone</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.password %></td>
      <td><%= user.usertype %></td>
      <td><%= user.fone %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/invite_signup.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h2>Continue register</h2>

    <%= form_for(@user, :url => users_invite_new_path, :html => {:method => :post}) do |f| %>
      <div class="field">
        <%= f.label :name %><br/>
        <%= f.text_field :name, :required => true, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :email %><br/>
        <%= f.email_field :email, :required => true, :readonly => true, :value => @id.email, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :token %><br/>
        <%= f.text_field :token, :required => true, :readonly => true, :value => @id.token, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :password %>
        <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br/>
        <%= f.password_field :password, autocomplete: "off", :required => true, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation %><br/>
        <%= f.password_field :password_confirmation, autocomplete: "off", :required => true, class: "form-control" %>
      </div>
      <div class="actions v-space">
        <%= f.submit "Complete sign up", class: "btn btn-info btn-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Log in") %>
<div class="container">
  <div class="d-flex flex-row justify-content-center row">
    <!--<p class="border-text"> or </p>-->
    <div class="col-sm-6 login-box">
      <h2>Sign up</h2>

      <%= render 'form', user: @user %>

      <p>Already an user? <%= link_to "Sign in here!", login_path, class: "sign-up" %></p>
    </div>

    <div class="col-sm-6 social-box">
      <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in", class: "btn social-button g-button" %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>User Type:</strong>
  <%= @user.usertype %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>