config/routes.rb
Rails.application.routes.draw do

  get 'visitors/index'
  root 'dashboard#dashboard'
  resources :windows
  resources :apps
  resources :users
  resources :sessions, only: [:create, :destroy]
  resources :dev_teams
  get 'dashboard' => 'dashboard#dashboard'
  get 'dashboard/listapps' => 'dashboard#list_apps'
  get 'current-dashboard' => 'dashboard#load_user_dashboard'
  post 'dashboard/new/:name' => 'dash_settings#create_user_dashboard'
  post 'dashboard/:dashid/delete' => 'dash_settings#delete_dashboard'
  
  get '/window-proxy' => 'dashboard#window_proxy'

  get 'invite/:rand_token', to: 'users#invite_signup'
  post 'users/invite/new', to: 'users#invite_signup2'
  get '/invite', to: 'users#develop_invite'
  post 'invite', to: 'users#develop_invite2'
  post 'invite_dev_to_team', to: 'dev_teams#invite_to_dev_team'
  get 'exclude_dev_from_team', to: 'dev_teams#exclude_from_dev_team'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create2'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get '/new-notification-request' => 'notification_request#new_request'
  get '/notification-requests' => 'notification_request#see_requests'
  get '/notification-requests/:token_id' => 'notification_request#edit_request'
  post '/notification-requests' => 'notification_request#post_request'
  get '/delete-notification-request/:token_id' => 'notification_request#delete_request'
  get '/delete-notification-app/:not_app_id' => 'notification_request#delete_request_app'
  get '/new-request-app' => 'notification_request#new_request_application'
  post '/request-app' => 'notification_request#post_request_application'

  post '/register-user' => 'notifications#register_user'
  get '/push-notification' => 'notifications#push_notification_form'

  post '/push-notification-send' => 'notifications#push_notification_send'
  get '/push-notification-send-requested' => 'notifications#push_notification_send_requested'

  get '/new-notifications' => 'notifications#new_notifications'
  get '/last-notifications' => 'notifications#last_notifications'
  get '/last-from-sampadash' => 'notifications#last_from_sampadash'
  get '/load-last-notifications' => 'notifications#load_last_notifications'
  get '/load-last-from-sampadash' => 'notifications#load_last_from_sampadash'

  get '/dash_settings' => 'dash_settings#settings'
  post '/set_new_dash/:dashid' => 'dash_settings#set_current_dash'

end

app/models/dev_team.rb
class DevTeam < ApplicationRecord
  has_many :dev_teams_users
  has_many :users, through: :dev_teams_users
  has_many :apps, dependent: :destroy
end

app/controllers/dev_teams_controller.rb
class DevTeamsController < ApplicationController
  before_action :set_dev_team, only: [:show, :edit, :update, :destroy, :invite_to_dev_team, :invite]

  # GET /dev_teams
  # GET /dev_teams.json
  def index
     #@dev_teams = DevTeam.all
    @dev_teams = current_user.dev_teams
  end

  # GET /dev_teams/1
  # GET /dev_teams/1.json
  def show
  end

  # GET /dev_teams/new
  def new
    @dev_team = DevTeam.new
  end

  # GET /dev_teams/1/edit
  def edit
  end

  # POST /dev_teams
  # POST /dev_teams.json
  def create
    @dev_team = DevTeam.new(dev_team_params)
    @dev_team_user = @dev_team.dev_teams_users.new(user_id: current_user.id)

    respond_to do |format|
      if @dev_team.save and @dev_team_user
        format.html { redirect_to @dev_team, notice: 'Dev team was successfully created.' }
        format.json { render :show, status: :created, location: @dev_team }
      else
        format.html { render :new }
        format.json { render json: @dev_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dev_teams/1
  # PATCH/PUT /dev_teams/1.json
  def update
    respond_to do |format|
      if @dev_team.update(dev_team_params)
        format.html { redirect_to @dev_team, notice: 'Dev team was successfully updated.' }
        format.json { render :show, status: :ok, location: @dev_team }
      else
        format.html { render :edit }
        format.json { render json: @dev_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dev_teams/1
  # DELETE /dev_teams/1.json
  def destroy
    @dev_team.destroy
    respond_to do |format|
      format.html { redirect_to dev_teams_url, notice: 'Dev team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def invite
    @dev_team = DevTeam.find(params[:id])
  end

  def invite_to_dev_team
    user = User.find_by_email(params[:email])
    if user
      dev_team_user = DevTeamsUser.new(dev_team_id: @dev_team.id, user_id: user.id)
      dev_team_user.save
      redirect_to dev_team_path(@dev_team), notice: 'User added in this Dev Team'
    else
      redirect_to controller: 'users', action: 'develop_invite', notice: 'User not found in Database. Please invite by email'
    end
  end

  def exclude_from_dev_team
    dev_team_user = DevTeamsUser.where(dev_team_id: params[:id], user_id: params[:user_id])
    dev_team_user.destroy_all
    redirect_to dev_team_path(id: params[:id]), notice: 'User excluded from this Dev Team'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dev_team
      @dev_team = DevTeam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dev_team_params
      params.require(:dev_team).permit(:name, :description)
    end
end

app/helpers/dev_teams_helper.rb
module DevTeamsHelper
end

app/views/dev_teams/_form.html.erb
<%= form_with(model: dev_team, local: true, class: 'form') do |form| %>
  <% if dev_team.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dev_team.errors.count, "error") %> prohibited this dev_team from being saved:</h2>

      <ul>
        <% dev_team.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, id: :dev_team_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_area :description, id: :dev_team_description, class: 'form-control' %>
  </div>

  <%= form.submit class: 'btn btn-primary btn-sm' %>

<% end %>

app/views/dev_teams/_invite.html.erb
<%= form_with(url: invite_dev_to_team_path(id: @dev_team.id), class: 'form-inline') do |form| %>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, placeholder: 'e.g. name@domain.com', required: true, id: :dev_team_email, class: 'form-control' %>
  </div>

  <%= form.submit 'Invite to this Team', class: 'btn btn-primary btn-sm' %>
<% end %>

app/views/dev_teams/edit.html.erb
<h1>Editing Dev Team</h1>
<%= link_to 'Show', @dev_team %> |
<%= link_to 'Back', dev_teams_path %>
<hr class="hr-main">

<div class="content">

  <%= render 'form', dev_team: @dev_team %>

</div>

app/views/dev_teams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Development Teams</h1>
<hr class="hr-main">

<div class="content">

  <table class="table table-hover">
    <thead>
    <tr>
      <th colspan="2" class="table-header">
        Development teams you participate:
      </th>
      <th class="btn-row">
        <%= link_to 'New Dev Team', new_dev_team_path, class: 'btn btn-primary btn-sm' %>
      </th>
    </tr>
    <tr>
      <th>Team Name</th>
      <th colspan="2">Description</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <% @dev_teams.each do |dev_team| %>
        <td>
          <h4><%= link_to dev_team.name, dev_team %></h4>
        </td>

        <td>
          <%= dev_team.description %>
        </td>

        <td class="btn-row">
          <%= link_to edit_dev_team_path(dev_team), {class: 'button edit', "data-tooltip": "Edit"} do %>
            <i class="fa fa-pencil fa-3x" aria-hidden="true"></i>
          <% end %>

          <%= link_to dev_team, {method: :delete, data: {confirm: 'Are you sure?'}, class: 'button delete', "data-tooltip": "Delete"} do %>
            <i class="fa fa-trash-o fa-3x" aria-hidden="true"></i>
          <% end %>
        </td>
      <% end %>
    </tr>
    </tbody>
  </table>
</div>

app/views/dev_teams/new.html.erb
<h1>New Dev Team</h1>
<%= link_to 'Back', dev_teams_path %>
<hr class="hr-main">

<div class="content">

  <%= render 'form', dev_team: @dev_team %>

</div>

app/views/dev_teams/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="dev-name">
  <%= @dev_team.name %>
</h1>

<p><%= @dev_team.description %></p>

<%= link_to 'Edit', edit_dev_team_path(@dev_team) %> |
<%= link_to 'Back', dev_teams_path %>

<hr class="hr-main">

<div class="content">

  <table class="table table-hover">
    <thead>
    <tr>
      <th colspan="2" class="table-header">
        Development Team:
      </th>
      <th class="btn-row">
        <%= render partial: 'invite' %>
      </th>
    </tr>
    <tr>
      <th>Name</th>
      <th colspan="2">Email</th>
    </tr>
    </thead>
    <tbody>
    <% @dev_team.users.each do |user| %>
      <tr>
        <td>
          <h4><%= user.name %></h4>
        </td>

        <td>
          <h4>
            <small><i><%= user.email %></i></small>
          </h4>
        </td>

        <td class="btn-row">
          <%= link_to exclude_dev_from_team_path(id: @dev_team.id, user_id: user.id), {class: 'button delete', "data-tooltip": "Delete"} do %>
            <i class="fa fa-trash-o fa-3x" aria-hidden="true"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <table class="table table-hover">
    <thead>
    <tr>
      <th colspan="3" class="table-header">
        Aplications:
      </th>
      <th class="btn-row">
        <%= link_to 'Register a new App', new_app_path(dev_team_id: @dev_team.id), class: 'btn btn-primary' %>
      </th>
    </tr>
    <tr>
      <th>Name</th>
      <th>Version</th>
      <th colspan="2">Description</th>
    </tr>
    </thead>
    <tbody>
    <% @dev_team.apps.each do |app| %>
      <tr>
        <td>
          <h4><%= app.name %></h4>
        </td>
        <td>
          <h4>
            <small><i><%= app.version %></i></small>
          </h4>
        </td>

        <td><%= app.description %></td>
        <td class="btn-row">
          <%= link_to edit_app_path(app), {class: 'button edit', "data-tooltip": "Edit"} do %>
            <i class="fa fa-pencil fa-3x" aria-hidden="true"></i>
          <% end %>
          <%= link_to app, {method: :delete, data: {confirm: 'Are you sure?'}, class: 'button delete', "data-tooltip": "Delete"} do %>
            <i class="fa fa-trash-o fa-3x" aria-hidden="true"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>