config/routes.rb
Rails.application.routes.draw do

  get 'visitors/index'
  root 'dashboard#dashboard'
  resources :windows
  resources :apps
  resources :users
  resources :sessions, only: [:create, :destroy]
  resources :dev_teams
  get 'dashboard' => 'dashboard#dashboard'
  get 'dashboard/listapps' => 'dashboard#list_apps'
  get 'current-dashboard' => 'dashboard#load_user_dashboard'
  post 'dashboard/new/:name' => 'dash_settings#create_user_dashboard'
  post 'dashboard/:dashid/delete' => 'dash_settings#delete_dashboard'
  
  get '/window-proxy' => 'dashboard#window_proxy'

  get 'invite/:rand_token', to: 'users#invite_signup'
  post 'users/invite/new', to: 'users#invite_signup2'
  get '/invite', to: 'users#develop_invite'
  post 'invite', to: 'users#develop_invite2'
  post 'invite_dev_to_team', to: 'dev_teams#invite_to_dev_team'
  get 'exclude_dev_from_team', to: 'dev_teams#exclude_from_dev_team'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create2'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get '/new-notification-request' => 'notification_request#new_request'
  get '/notification-requests' => 'notification_request#see_requests'
  get '/notification-requests/:token_id' => 'notification_request#edit_request'
  post '/notification-requests' => 'notification_request#post_request'
  get '/delete-notification-request/:token_id' => 'notification_request#delete_request'
  get '/delete-notification-app/:not_app_id' => 'notification_request#delete_request_app'
  get '/new-request-app' => 'notification_request#new_request_application'
  post '/request-app' => 'notification_request#post_request_application'

  post '/register-user' => 'notifications#register_user'
  get '/push-notification' => 'notifications#push_notification_form'

  post '/push-notification-send' => 'notifications#push_notification_send'
  get '/push-notification-send-requested' => 'notifications#push_notification_send_requested'

  get '/new-notifications' => 'notifications#new_notifications'
  get '/last-notifications' => 'notifications#last_notifications'
  get '/last-from-sampadash' => 'notifications#last_from_sampadash'
  get '/load-last-notifications' => 'notifications#load_last_notifications'
  get '/load-last-from-sampadash' => 'notifications#load_last_from_sampadash'

  get '/dash_settings' => 'dash_settings#settings'
  post '/set_new_dash/:dashid' => 'dash_settings#set_current_dash'

end

app/models/app.rb
class App < ApplicationRecord
  has_many :windows, dependent: :destroy
  belongs_to :dev_team
  validates :name, presence: true
  validates :version, presence: true
  validates :description, presence: true
  validates :base_url, presence: true
  validates :grid_size, presence: true
  validates :parameters, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dev_team.rb
class DevTeam < ApplicationRecord
  has_many :dev_teams_users
  has_many :users, through: :dev_teams_users
  has_many :apps, dependent: :destroy
end

app/models/dev_teams_user.rb
class DevTeamsUser < ApplicationRecord
  belongs_to :user
  belongs_to :dev_team
end

app/models/notification_app.rb
class NotificationApp < ApplicationRecord

  belongs_to :app

end

app/models/notification_token.rb
class NotificationToken < ApplicationRecord

  belongs_to :user
  validates_uniqueness_of :token
  has_many :notification_apps

  RequestedState = '1' # user requests a notification
  SendState = '2' # notification is sent by Infocity
  SeenState = '3' # notification was seen by user

end

app/models/push_notification.rb
class PushNotification < ApplicationRecord
end

app/models/token.rb
class Token < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  has_many :user_dashboards, dependent: :destroy
  has_many :dev_teams_users
  has_many :dev_teams, through: :dev_teams_users


  def self.from_omniauth(auth)
    user = User.find_by_email (auth.info.email)
    if (user)
      return user;
    end
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.email = auth.info.email
      user.usertype = 0
      user.save!
      dashboard = UserDashboard.new user_id: user.id, description: 'Default'
      dashboard.save!
    end
  end
end

app/models/user_dashboard.rb
class UserDashboard < ApplicationRecord
  belongs_to :user
  has_many :windows, dependent: :destroy

  validates_presence_of :description, message: 'Missing dashboard description'
  validates_length_of :description, :maximum => 15, :allow_blank => false
end

app/models/window.rb
class Window < ApplicationRecord
  belongs_to :app
  belongs_to :user_dashboard
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController

  before_action :authenticate_user, only: [:index, :show, :new, :edit, :destroy]
  before_action :has_dev_permissions, only: [:show, :new, :edit, :update, :destroy]
  before_action :set_app, only: [:show, :edit, :update, :destroy]
  before_action :set_dashboard
  before_action :set_dev_team

  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
  end

  # GET /apps/new
  def new
    @app = App.new
  end

  # GET /apps/1/edit
  def edit
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = current_dev_team.apps.new(app_params)
    respond_to do |format|
      if @app.save
        format.html {redirect_to @app, notice: 'App was successfully created.'}
        format.json {render :show, status: :created, location: @app}
      else
        format.html {render :new}
        format.json {render json: @app.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /apps/1
  # PATCH/PUT /apps/1.json
  def update
    respond_to do |format|
      if @app.update(app_params)
        format.html {redirect_to @app, notice: 'App was successfully updated.'}
        format.json {render :show, status: :ok, location: @app}
      else
        format.html {render :edit}
        format.json {render json: @app.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app.destroy
    respond_to do |format|
      format.html {redirect_back fallback_location: apps_url, notice: 'App was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_app
    @app = App.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def app_params
    params.require(:app).permit(:name, :version, :description, :base_url, :grid_size, :parameters)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/dev_teams_helper.rb
module DevTeamsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/helpers/windows_helper.rb
module WindowsHelper
end

app/views/apps/_app.html.erb
<h1><%= app.name %>
  <small><%= app.version %></small>
</h1>
<h5><%= app.description %></h5>

app/views/apps/_form.html.erb
<%= form_with(model: app, local: true) do |form| %>
  <% if app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
        <% app.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, placeholder: 'Add your App name. Example: Youtube App', id: :app_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :version, class: 'form-label' %>
    <%= form.text_field :version, placeholder: 'Add a version of your App. Example: 1.3', id: :app_version, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_area :description, placeholder: 'Add some description about your App.', id: :app_description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :base_url, class: 'form-label' %>
    <%= form.text_field :base_url, placeholder: 'Add url for query. Example: http://get-youtube.herokuapp.com', id: :app_base_url, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :grid_size, class: 'form-label' %>
    <%= form.text_field :grid_size, placeholder: 'Add an initial size of your App in Gridsize. Example: 3x2', id: :app_grid_size, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :parameters, class: 'form-label' %>
    <%= form.text_field :parameters, placeholder: 'Add an Hash with key as key params and value as form field. Example: { video_url: "text_field" } will create a text field form with video_url as params.', id: :app_parameters, class: 'form-control' %>
  </div>

  <%= form.submit class: 'btn btn-primary btn-sm' %>

<% end %>

app/views/apps/edit.html.erb
<h1>Editing App</h1>
<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

<hr class="hr-main">

<div class="content">
  <%= render 'form', app: @app %>
</div>

app/views/apps/index.html.erb
<div class="index">
  <p id="notice"><%= notice %></p>

  <h1>Choose an Application:</h1>

  <hr class="hr-main">

  <div class="content">

    <ul>
      <% @apps.each do |app| %>
        <%= link_to controller: 'windows', action: 'new', app_id: app.id, user_dashboard_id: current_dashboard.id do %>
          <li>
            <h4> <%= app.name %>
              <small><i><%= app.version %></i></small>
            </h4>
            <p><b><%= app.dev_team.name %></b></p>
            <p><%= app.description %></p>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/apps/new.html.erb
<h1>New App</h1>
<%= link_to 'Back', apps_path %>

<hr class="hr-main">

<div class="content">
  <%= render 'form', app: @app %>
</div>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @app.name %>
</p>

<p>
  <strong>Version:</strong>
  <%= @app.version %>
</p>

<p>
  <strong>Description:</strong>
  <%= @app.description %>
</p>

<p>
  <strong>Base url:</strong>
  <%= @app.base_url %>
</p>

<p>
  <strong>Grid size:</strong>
  <%= @app.grid_size %>
</p>

<p>
  <strong>Parameters:</strong>
  <%= @app.parameters %>
</p>

<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', dev_team_path(@app.dev_team_id) %>

app/views/layouts/_nav_side_menu.html.erb
<div id="nav-side-menu" class="nav-side-menu">
  <div class="menu-list">

    <ul id="menu-content" class="menu-content collapse out">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">
        <li>
          <i class="fa fa-arrows-alt fa-lg" aria-hidden="true"></i> Fullscreen
        </li>
      </a>

      <a href="/">
        <li>
          <i class="fa fa-dashboard fa-lg"></i>
          <% if current_dashboard %>
            <%= current_dashboard.description %> Dash
          <% else %>
            Unexpected Error - controllers should to set current_dashboard appropriately
          <% end %>
        </li>
      </a>

      <li data-toggle="collapse" data-target="#side-menu-app" class="collapsed">
        <i class="fa fa-bar-chart fa-lg"></i> Application <span class="arrow"></span>
      </li>

      <% if current_dashboard %>
        <ul class="sub-menu collapse" id="side-menu-app">
          <%= link_to controller: 'apps', action: 'index',
                      user_dashboard_id: current_dashboard.id,
                      id: 'new_window_link' do %>
            <li id="new_window_link">
              New window
            </li>
          <% end %>
        </ul>
      <% end %>


      <li data-toggle="collapse" data-target="#side-menu-notification" class="collapsed"
          id="notifications_link">
        <i class="fa fa-bell fa-lg" id="notification_normal"></i>
        <i class="fa fa-exclamation-circle fa-lg" id="notification_alert"></i>
        Notification <span class="arrow"></span>
      </li>
      <ul class="sub-menu collapse" id="side-menu-notification">
        <a href="/new-notification-request">
          <li>New Notification Request</li>
        </a>
        <a href="/notification-requests">
          <li>My Notification Requests</li>
        </a>
        <a href="/last-notifications" id="lost_notifications_link">
          <li>Last Notifications</li>
        </a>
        <a href="/last-from-sampadash" id="last_24h_link">
          <li>Last 24h from SampaDash</li>
        </a>
      </ul>

      <a href="/dash_settings">
        <li>
          <i class="fa fa-wrench fa-lg"></i> SampaDash Options
        </li>
      </a>

    </ul>

    </ul>
  </div>
</div>

<div id="fullalert" class="alert alert-info full-alert">
  Press <strong>esc</strong> to exit fullscreen
</div>

<script>

  function openNav() {
    document.getElementById("nav-side-menu").style.marginLeft = "0";
    document.getElementById("main").style.marginLeft = "200px";
    document.getElementById("navbar").style.marginTop = "0";
    document.getElementsByTagName("BODY")[0].style.paddingTop = "65px";
  }

  function closeNav() {
    document.getElementById("nav-side-menu").style.marginLeft = "-200px";
    document.getElementById("main").style.marginLeft = "0";
    document.getElementById("navbar").style.marginTop = "-50px";
    document.getElementsByTagName("BODY")[0].style.paddingTop = "15px";

    var el = document.documentElement,
      rfs = // for newer Webkit and Firefox
        el.requestFullScreen
        || el.webkitRequestFullScreen
        || el.mozRequestFullScreen
        || el.msRequestFullScreen
    ;
    if (typeof rfs != "undefined" && rfs) {
      rfs.call(el);
    } else if (typeof window.ActiveXObject != "undefined") {
      // for Internet Explorer
      var wscript = new ActiveXObject("WScript.Shell");
      if (wscript != null) {
        wscript.SendKeys("{F11}");
      }
    }

    document.getElementById("fullalert").style.display = "block";
    setTimeout(function () {
      document.getElementById("fullalert").style.display = "none";
    }, 3000);
  }

  document.addEventListener('fullscreenchange', exitHandler);
  document.addEventListener('webkitfullscreenchange', exitHandler);
  document.addEventListener('mozfullscreenchange', exitHandler);
  document.addEventListener('MSFullscreenChange', exitHandler);

  function exitHandler() {
    if (!document.fullscreenElement && !document.webkitIsFullScreen && !document.mozFullScreen && !document.msFullscreenElement) {
      openNav();
    }
  }
</script>

app/views/layouts/_navbar.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<nav class="navbar navbar-default navbar-fixed-top" id="navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        SAMPADASH
      </a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <% if current_user.usertype == 1 %>
            <li>
              <%= link_to 'Invite Developer', controller: 'users', action: 'develop_invite' %>
            </li>

            <li>
              <%= link_to 'Your Development Teams', dev_teams_path(user_id: current_user.id) %>
            </li>
          <% end %>
          <li>
            <%= link_to 'Sign out', signout_path %>
          </li>

        <% else %>
          <li>
            <%= link_to 'Sign in', controller: 'sessions', action: 'new' %>
          </li>

          <!--<li>
              <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
            </li>-->

          <li>
            <%= link_to "Sign up", controller: 'users', action: 'new' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampaDashboard</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <script src="https://www.gstatic.com/firebasejs/3.9.0/firebase.js"></script>
  <script src="https://www.gstatic.com/firebasejs/3.9.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/3.9.0/firebase-messaging.js"></script>
  <script>
    csrfToken = "<%= form_authenticity_token.to_s %>";
  </script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<header>
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/nav_side_menu' if current_user %>
</header>

<main id='main' style="<%= 'margin-left: 200px' if current_user %>">
  <%= yield %>
</main>

</body>
</html>

app/views/layouts/notification-request.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampaDashboard</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://capella.pro/mapa/min.css">
  <script src="https://www.gstatic.com/firebasejs/3.9.0/firebase.js"></script>
  <script src="https://www.gstatic.com/firebasejs/3.9.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/3.9.0/firebase-messaging.js"></script>
  <script>
    csrfToken = "<%= form_authenticity_token.to_s %>";
  </script>
  <%= javascript_include_tag 'jquery-3.2.1.min', 'data-turbolinks-track': 'reload' %>
  <script src="https://capella.pro/mapa/min.js"></script>
  <%= javascript_include_tag 'bootstrap-sprockets', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'notifications-fallback', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'firebase-config', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<header>
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/nav_side_menu' if current_user %>
</header>

<main id='main' style="<%= 'margin-left: 200px' if current_user %>">
  <%= yield %>
</main>

</body>
</html>